[package]
name = "book-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = "0.21.0"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
wasm-pack = "0.13"